frase = '     Curso em Video Python    '
dividido = frase.split()
#print (frase)
#print (frase[3])
#print (frase[3:13])
#print(frase[:13])
#print(frase[13:])
#print(frase[1:15])
#print(frase[1:15:2])
#print(frase[:15:2])
#print(frase[::2])
#print(frase.count('o'))
#print(frase.upper().count('o'))
#print(len(frase))
#Se colocar espaços antes e depois da frase
#print(len(frase.strip()))
#print(frase.replace('Python','Ricardo'))
#print(frase.strip().replace('Python','Ricardo'))
#print('Curso' in frase)
#print(frase.find('Curso'))#o valor 5 é devido aos espaços
#print(frase.find('video'))
#print(frase.lower().find('video'))
#print(frase.split())
print(dividido)
print(dividido[0])
#print(dividido[2][3])